const assert = require('node:assert/strict')
const fs = require('node:fs')
const path = require('node:path')
const test = require('node:test')

const adminSource = path.resolve(__dirname, '../admin/src')
const markup = fs.readFileSync(path.join(adminSource, 'index.html'), 'utf8')
const articleScript = fs.readFileSync(path.join(adminSource, 'article-manager.js'), 'utf8')
const mainScript = fs.readFileSync(path.join(adminSource, 'main.js'), 'utf8')
const importScript = fs.readFileSync(path.join(adminSource, 'import.js'), 'utf8')
const styles = fs.readFileSync(path.join(adminSource, 'styles.css'), 'utf8')
const routesSource = fs.readFileSync(path.resolve(__dirname, '../src/routes.js'), 'utf8')

test('文章新增和编辑复用双栏弹窗，保存后原地刷新列表', () => {
  assert.doesNotMatch(markup, /id="article-editor"/)
  assert.match(markup, /id="articleEditorModal"[^>]*role="dialog"/)
  assert.match(markup, /class="article-editor-main"[\s\S]*id="articleTitleInput"[\s\S]*id="articleBodyEditor"/)
  assert.match(markup, /class="article-editor-meta"[\s\S]*id="articleCoverPreview"[\s\S]*class="article-editor-meta-row"[\s\S]*id="articleAuthorInput"[\s\S]*id="articlePublishAtInput"[\s\S]*id="articleEditorPreviewBody"/)
  assert.match(markup, /class="article-editor-meta-row"[\s\S]*class="form-field"[\s\S]*id="articleAuthorInput"[\s\S]*class="form-field article-editor-publish-row"[\s\S]*id="articlePublishAtInput"/)
  assert.match(styles, /\.article-editor-meta-row\s*\{[\s\S]*grid-template-columns:\s*minmax\(0, 0\.8fr\) minmax\(0, 1\.2fr\)/)
  assert.doesNotMatch(markup, /article-editor-meta-row[\s\S]*<label for="article(?:Author|PublishAt)Input"/)
  const metaRowStart = styles.indexOf('.article-editor-meta-row {')
  const metaRowEnd = styles.indexOf('.article-editor-meta-row .article-editor-publish-row input')
  assert.ok(metaRowStart >= 0 && metaRowEnd > metaRowStart)
  assert.doesNotMatch(styles.slice(metaRowStart, metaRowEnd), /border-left:/)
  assert.match(styles, /\.article-editor-meta-row \.article-editor-publish-row input\s*\{[\s\S]*min-width:\s*0;[\s\S]*font-size:\s*12px;/)
  assert.match(styles, /\.modal-body\.article-editor-modal-body\s*\{[\s\S]*width:\s*min\(900px,\s*calc\(100vw - 64px\)\)/)
  assert.match(styles, /\.article-editor-grid\s*\{[\s\S]*grid-template-columns:\s*minmax\(0, 55fr\) minmax\(0, 45fr\)/)
  const editorMainStart = markup.indexOf('class="article-editor-main"')
  const editorMetaStart = markup.indexOf('class="article-editor-meta"')
  assert.ok(editorMainStart >= 0 && editorMetaStart > editorMainStart)
  assert.doesNotMatch(markup.slice(editorMainStart, editorMetaStart), /id="articleAuthorInput"/)
  assert.match(articleScript, /function openEditor\(article = emptyArticle\(\), mode = 'content'\)/)
  assert.match(articleScript, /openModal\(nodes\.editorModal\)/)
  assert.match(articleScript, /await closeEditor\(\)[\s\S]*await loadArticles\(\)/)
  assert.doesNotMatch(articleScript, /showSection\?\.\('article-editor'\)/)
})

test('统一文章弹窗上传本地封面并自动绑定图片素材', () => {
  assert.match(markup, /id="articleCoverUploadInput"[^>]*type="file"/)
  assert.match(markup, /id="articleCoverUploadInput"[^>]*accept="image\/jpeg,image\/png,image\/webp,.jpg,.jpeg,.png,.webp"/)
  assert.match(markup, /id="articleCoverUploadBtn"[^>]*aria-label="上传封面"[^>]*title="上传封面"/)
  assert.match(markup, /id="articleCoverRemoveBtn"[^>]*aria-label="删除封面"[^>]*title="删除封面"/)
  assert.match(markup, /Lucide Static v0\.468\.0 \(ISC\): image-up, trash-2/)
  assert.match(markup, /class="article-cover-preview"[\s\S]*class="article-cover-tools"[\s\S]*id="articleCoverUploadBtn"[\s\S]*id="articleCoverRemoveBtn"/)
  assert.match(markup, /id="articleCoverUploadStatus"[^>]*aria-live="polite"/)
  assert.doesNotMatch(markup, /placeholder="输入图片素材 ID"/)
  assert.match(articleScript, /async function uploadCover\(file\)/)
  assert.match(articleScript, /isArticleCoverFile\(file\)/)
  assert.match(articleScript, /uploadImageFileToCos\(file, \{[\s\S]*usage: 'article'/)
  assert.match(articleScript, /nodes\.cover\.value = coverImage\.id/)
  assert.match(articleScript, /已上传并选为文章封面/)
  assert.match(articleScript, /state\.uploadingCover \|\| !file/)
  assert.match(articleScript, /nodes\.coverUploadButton\.disabled = true/)
  assert.match(articleScript, /nodes\.coverUpload\.value = ''/)
  assert.doesNotMatch(articleScript, /当前文章封面已绑定|未选择封面/)
  assert.match(styles, /\.article-cover-upload-status\s*\{[\s\S]*position:\s*absolute;[\s\S]*width:\s*1px;[\s\S]*height:\s*1px;/)
  assert.match(styles, /\.article-cover-tools\s*\{[\s\S]*position:\s*absolute;[\s\S]*top:\s*8px;[\s\S]*right:\s*8px;[\s\S]*display:\s*flex;[\s\S]*gap:\s*6px;/)
  assert.match(styles, /\.article-cover-tool-button\s*\{[\s\S]*width:\s*32px;[\s\S]*height:\s*32px;[\s\S]*background:\s*rgba\(25, 25, 25, 0\.45\);/)
  assert.match(styles, /\.article-cover-tool-button--danger\s*\{[\s\S]*background:\s*rgba\(217, 54, 62, 0\.72\);/)
  assert.match(markup, /class="article-editor-meta-row"[\s\S]*class="form-field article-editor-publish-row"><input id="articlePublishAtInput" type="datetime-local" aria-label="发布时间"/)
  assert.match(articleScript, /\/api\/admin\/images\/reclaim/)
  assert.match(articleScript, /state\.editorUploadedCoverIds/)
  assert.match(articleScript, /state\.importTransientCoverIds/)
  assert.match(routesSource, /router\.post\('\/api\/admin\/images\/reclaim'[\s\S]*reclaimImageAssets\(ids\)/)
})

test('文章封面保留原始构图，固定比例只在展示层裁切', () => {
  assert.doesNotMatch(mainScript, /if \(usage === 'article'/)
  assert.doesNotMatch(mainScript, /canvas\.toBlob\(/)
  assert.match(mainScript, /fixed-ratio previews and cards crop visually without changing the source/)
  assert.match(styles, /\.article-cover-media img\s*\{[\s\S]*object-fit:\s*cover/)
})

test('文章阅读预览使用浏览器支持的日期时间格式', () => {
  assert.match(articleScript, /dateStyle:\s*'medium',[\s\S]*timeStyle:\s*'short'/)
  assert.doesNotMatch(articleScript, /dateStyle:\s*'medium',[\s\S]{0,120}(?:hour|minute):/)
})

test('文章列表支持标题、标签和发布时间行内编辑并一次保存本页修改', () => {
  assert.match(markup, /id="articleListSaveBtn"[^>]*disabled>保存<\/button>/)
  assert.match(articleScript, /state\.items\.map\(\(item, index\) =>/)
  assert.match(articleScript, /<td data-label="ID">\$\{\(state\.page - 1\) \* state\.pageSize \+ index \+ 1\}<\/td>/)
  assert.doesNotMatch(articleScript, /<td data-label="ID"[^>]*>\$\{escapeHtml\(item\.id\)\}<\/td>/)
  assert.doesNotMatch(articleScript, /<td data-label="ID"[^>]*title=/)
  assert.match(markup, /<th>标题<\/th><th>作者<\/th><th>封面<\/th>/)
  assert.match(articleScript, /<td data-label="标题"><input class="article-list-title"/)
  assert.doesNotMatch(articleScript, /articleSourceLabel|article-list-source|data-label="文章"/)
  assert.match(styles, /\.article-list-author\s*\{[\s\S]*width: 100%;[\s\S]*max-width: 100%;[\s\S]*min-width: 0;[\s\S]*box-sizing: border-box;/)
  assert.match(styles, /\.article-table td\[data-label="封面"\]\s*\{[\s\S]*overflow: hidden;/)
  assert.match(styles, /\.article-table td\[data-label="封面"\] \.article-list-cover-link,[\s\S]*max-width: 100%;[\s\S]*margin-inline: auto;/)
  assert.match(articleScript, /data-article-title=/)
  assert.match(articleScript, /data-article-label=/)
  assert.match(articleScript, /class="content-label-input"/)
  assert.match(articleScript, /data-article-published-at=/)
  assert.doesNotMatch(articleScript, /articlePublishState|class="article-list-publish"|已发布|待发布|待设置|待检查/)
  assert.match(articleScript, /<td data-label="发布时间"><input class="article-list-published-at" type="datetime-local" data-article-published-at=/)
  assert.doesNotMatch(styles, /\.article-list-publish(?:\s|\.)/)
  assert.doesNotMatch(`${markup}\n${articleScript}`, /data-article-excerpt|data-article-recommended|articleSummaryInput|articleRecommendedInput/)
  assert.match(articleScript, /async function saveInlineArticles\(\)/)
  assert.match(articleScript, /nodes\.listSave\.addEventListener\('click', saveInlineArticles\)/)
  assert.match(articleScript, /articlePath\(`\/\$\{encodeURIComponent\(article\.id\)\}`\)/)
  assert.match(articleScript, /请填写有效的标题和发布时间/)
  assert.match(articleScript, /state\.dirty\.clear\(\)/)
  assert.match(articleScript, /data-article-label[\s\S]*updateInlineArticle\(label\.dataset\.articleLabel, \{ label: label\.value \}\)/)
})

test('公众号文章批量导入复用导入内容页，按钮使用统一文案', () => {
  assert.match(markup, /id="articleUrlImportBtn"[^>]*>批量导入</)
  assert.match(markup, /id="articleUrlImportPanel"/)
  assert.match(markup, /class="article-url-import-stack"/)
  assert.match(markup, /class="panel article-import-input-panel"[\s\S]*id="articleImportStartBtn"[^>]*>立即抓取<[\s\S]*id="articleImportUrls"[^>]*aria-label="文章链接"/)
  assert.match(styles, /\.article-import-input-panel #articleImportStartBtn \{\s*font-size: var\(--font-body\);\s*\}/)
  assert.match(markup, /class="panel article-import-results-panel"[\s\S]*id="articleImportSummary"[^>]*>等待提交链接[\s\S]*id="articleImportValidCount"[^>]*>0 篇可导入[\s\S]*id="articleImportPublishBtn"[^>]*>确认导入全部 0 篇<[\s\S]*id="articleImportList"/)
  assert.match(markup, /class="btn-primary hidden"[^>]*id="articleImportPublishBtn"/)
  assert.ok(markup.indexOf('article-import-input-panel') < markup.indexOf('article-import-results-panel'))
  const tabs = markup.match(/<div class="import-type-tabs"[\s\S]*?<\/div>/)?.[0] || ''
  ;['text', 'audio', 'album', 'article', 'letter-copy'].forEach((type) => {
    assert.match(tabs, new RegExp(`data-import-type="${type}"`))
  })
  assert.ok(tabs.indexOf('data-import-type="article"') < tabs.indexOf('data-import-type="letter-copy"'))
  assert.match(importScript, /article:\s*{[\s\S]*?source:\s*'article'/)
  assert.match(importScript, /type === 'article'[\s\S]*?new CustomEvent\('open-article-import'/)
  assert.match(articleScript, /function openArticleImport\(\)/)
  assert.match(articleScript, /nodes\.importOpen\.addEventListener\('click',[\s\S]*?type: 'article'/)
  assert.match(articleScript, /window\.addEventListener\('open-article-import', openArticleImport\)/)
  assert.match(articleScript, /window\.addEventListener\('close-article-import', closeArticleImport\)/)
  assert.match(articleScript, /function openArticleImport\(\)\s*\{\s*resetImportWorkspace\(\)/)
  assert.match(articleScript, /nodes\.importStart\.textContent = '立即抓取'/)
  assert.match(articleScript, /nodes\.importStart\.textContent = '重新抓取'/)
  assert.doesNotMatch(articleScript, /nodes\.importStart\.textContent = '重新提交'/)
  assert.match(articleScript, /nodes\.importStart\.textContent = '抓取中…'/)
  assert.match(articleScript, /共 \$\{total\} 篇 · 可导入 \$\{ready\}/)
  assert.match(articleScript, /\$\{ready\} 篇可导入/)
  assert.match(articleScript, /失败 \$\{failed\}/)
  assert.match(articleScript, /重复 \$\{duplicate\}/)
  assert.match(markup, /class="article-import-result-actions"[\s\S]*id="articleImportValidCount"[\s\S]*id="articleImportPublishBtn"/)
  assert.doesNotMatch(markup, /class="article-import-summary"/)
  assert.doesNotMatch(styles, /\.article-import-summary\s*\{/)
  assert.doesNotMatch(markup, /<label for="articleImportUrls">文章链接<\/label>/)
  assert.match(importScript, /sourceHint: '按子目录或“名称 \+ 序号”分组，每组 1-9 张。'/)
  assert.match(styles, /#import\.article-url-import-active \.import-source-panel,[\s\S]*#import\.article-url-import-active \.import-preview-panel/)
  assert.doesNotMatch(styles, /#import\.article-url-import-active \.import-(?:type-tabs|section-head)/)
  assert.match(styles, /\.article-import-list > \.import-empty\s*\{\s*grid-column:\s*1 \/ -1;/)
  assert.doesNotMatch(markup, /id="articleImportBackBtn"/)
})

test('四类内容卡片都提供统一刷新入口并调用内容加载', () => {
  ;['contentTexts', 'contentAudios', 'contentAlbums', 'letters'].forEach((type) => {
    assert.match(markup, new RegExp(`data-content-refresh="${type}"`))
  })
  assert.match(mainScript, /function refreshContentEditor\(button\)/)
  assert.match(mainScript, /document\.querySelectorAll\('\[data-content-refresh\]'\)/)
  assert.match(mainScript, /const loaded = await loadContentEditor\(\)/)
})
