const assert = require('node:assert/strict')
const fs = require('node:fs')
const path = require('node:path')
const test = require('node:test')

const source = path.resolve(__dirname, '../admin/src')
const markup = fs.readFileSync(path.join(source, 'index.html'), 'utf8')
const script = fs.readFileSync(path.join(source, 'article-manager.js'), 'utf8')
const mainScript = fs.readFileSync(path.join(source, 'main.js'), 'utf8')
const styles = fs.readFileSync(path.join(source, 'styles.css'), 'utf8')

test('article import results keep fixed-size phone cards and add columns on wider screens', () => {
  assert.match(styles, /\.article-import-list\s*\{[\s\S]*grid-template-columns:\s*repeat\(auto-fill,\s*var\(--article-import-card-width\)\)[\s\S]*width:\s*100%;[\s\S]*min-width:\s*0/)
  assert.match(styles, /\.article-import-entry\s*\{[\s\S]*width:\s*100%;[\s\S]*min-width:\s*0;[\s\S]*height:\s*auto/)
  assert.doesNotMatch(styles, /\.article-import-entry\s*\{[^}]*?(?:border|background|padding):/)
  assert.match(styles, /\.article-import-reading-card-viewport\s*\{[\s\S]*aspect-ratio:\s*375\s*\/\s*667;[\s\S]*container-type:\s*inline-size/)
  assert.match(styles, /\.article-reading-card-scroll\s*\{[\s\S]*overflow-x:\s*hidden;[\s\S]*overflow-y:\s*auto/)
  assert.match(styles, /\.article-reading-card-scroll img,[\s\S]*width:\s*100%;[\s\S]*max-width:\s*100%/)
  assert.match(styles, /\.article-reading-card-scroll img\.article-reading-cover\s*\{[\s\S]*object-fit:\s*cover/)
  assert.match(styles, /\.article-reading-body img,[\s\S]*width:\s*100%;[\s\S]*height:\s*auto/)
  assert.doesNotMatch(styles, /\.article-import-item/)
  assert.match(styles, /\.article-reading-card-scroll\.article-reading-preview\s*\{[\s\S]*gap:\s*clamp\([\s\S]*padding:\s*clamp\(/)
  assert.match(styles, /\.article-reading-preview h1\s*\{[\s\S]*font-size:\s*22px;[\s\S]*line-height:\s*1\.38[\s\S]*-webkit-line-clamp:\s*2/)
  assert.match(styles, /\.article-reading-card-scroll\.article-reading-preview h1\s*\{[\s\S]*font-size:\s*clamp\(16px,\s*4\.27cqi,\s*20px\)[\s\S]*line-height:\s*1\.48/)
  assert.match(styles, /\.article-reading-card-scroll \.article-reading-meta\s*\{[\s\S]*font-size:\s*clamp\(12px,\s*3\.73cqi,\s*15px\)/)
  assert.match(styles, /\.article-reading-card-scroll \.article-reading-body\s*\{[\s\S]*font-size:\s*16px/)
  assert.match(styles, /\.article-import-tool-button\s*\{[\s\S]*width:\s*clamp\(34px,\s*10\.13cqi,\s*42px\)[\s\S]*font-size:\s*clamp\(18px,\s*5\.33cqi,\s*22px\)/)
})

test('article import preview preserves recoverable legacy article covers before display variants', () => {
  assert.match(script, /function coverImageUrl\(coverImage\)/)
  assert.match(script, /!coverImage\.processingProfile && coverImage\.usage === 'article' && coverImage\.originalUrl/)
  assert.match(script, /coverImage\.mediumUrl \|\| coverImage\.thumbUrl \|\| coverImage\.originalUrl/)
  assert.match(script, /function renderReadingHeader\(\{[\s\S]*coverUrl = ''[\s\S]*\}\s*= \{\}\)/)
  assert.match(script, /<img class="article-reading-cover" src="\$\{escapeHtml\(coverUrl\)\}"/)
  assert.ok((script.match(/renderReadingHeader\(/g) || []).length >= 4)
  assert.match(markup, /id="articlePreviewHeader"/)
  assert.match(markup, /id="articleEditorPreviewHeader"/)
  assert.doesNotMatch(markup, /id="articlePreviewCover"|id="articleEditorPreviewCover"/)
})

test('article reading previews use a compact title-cover header with inline author and time', () => {
  assert.match(styles, /.article-reading-header\s*\{[\s\S]*display:\s*grid;[\s\S]*grid-template-columns:\s*minmax\(0,\s*1fr\) minmax\(88px,\s*32%\)/)
  assert.match(styles, /.article-reading-header \.article-reading-cover\s*\{[\s\S]*height:\s*auto;[\s\S]*border-radius:\s*6px/)
  assert.match(styles, /.article-reading-cover\s*\{[\s\S]*aspect-ratio:\s*196\s*\/\s*132/)
  assert.match(styles, /.article-reading-meta\s*\{[\s\S]*justify-content:\s*flex-start;[\s\S]*gap:\s*8px[\s\S]*flex-wrap:\s*nowrap/)
  assert.doesNotMatch(styles, /.article-reading-meta\s*\{[^}]*justify-content:\s*space-between/)
  assert.match(script, /renderReadingHeader\(\{ title, author: item\.author, publishedAt: item\.publishedAt, metaText: fallbackMeta, coverUrl \}\)/)
  assert.match(script, /article-reading-header--stacked/)
})

test('article import cards keep successful items by default and expose direct edit and removal tools', () => {
  assert.doesNotMatch(script, /data-import-article=|data-import-confirm=|采用当前版本|待确认|_confirmed/)
  assert.doesNotMatch(script, /article-import-card-head|article-import-card-source|importStatusLabel/)
  assert.match(script, /<article class="article-import-entry article-import-entry--\$\{escapeHtml\(item\.status\)\}">\s*<div class="article-import-reading-card-viewport">/)
  assert.match(script, /data-import-edit=/)
  assert.match(script, /data-import-remove=/)
  assert.match(script, /Lucide Static v0\.468\.0/)
  assert.match(script, /importToolIcons\.delete/)
  assert.match(script, /importToolIcons\.edit/)
  assert.match(script, /importToolIcons\.retry/)
  assert.doesNotMatch(script, /data-import-remove=[^>]+>×<\/button>/)
  assert.match(script, /aria-label="编辑当前文章" title="编辑当前文章"/)
  assert.match(script, /aria-label="从本批次移除" title="从本批次移除"/)
  assert.ok(script.indexOf('data-import-remove=') < script.indexOf('data-import-edit='))
  assert.match(script, /const canEdit = item\.status === 'success'/)
  assert.match(script, /const canRemove = \['success', 'failed', 'duplicate'\]\.includes\(item\.status\)/)
  assert.match(script, /function removeImportItem\(id\)[\s\S]*state\.importItems\.splice\(index, 1\)[\s\S]*state\.removedImportIds\.add\(id\)[\s\S]*renderImportItems\(\)/)
  const importClickHandler = script.slice(script.indexOf("nodes.importList.addEventListener('click'"), script.indexOf("nodes.previewRestoreTail.addEventListener"))
  assert.match(importClickHandler, /else if \(remove && article\) \{\s*removeImportItem\(id\)/)
  assert.doesNotMatch(importClickHandler, /openConfirm|confirmModal/)
  assert.match(script, /nodes\.importValidCount\.textContent = `\$\{success\} 篇可导入`/)
  assert.match(script, /nodes\.importPublish\.classList\.toggle\('hidden', !state\.importItems\.some\(\(item\) => item\.status === 'success'\)\)/)
  assert.match(script, /state\.importJobId \? '本批次已清空' : '等待提交链接'/)
  assert.match(script, /恢复已移除文字/)
  assert.match(script, /editedItems/)
  assert.match(script, /const selectedIds = state\.importItems\.filter\(\(item\) => item\.status === 'success'\)\.map\(\(item\) => item\.id\)/)
  assert.match(script, /title: String\(item\.title \|\| ''\)\.trim\(\)/)
  assert.match(script, /bodyMarkdown: String\(item\.bodyMarkdown \|\| ''\)\.trim\(\)/)
})

test('failed article previews keep the phone viewport and retry only their current URL', () => {
  assert.match(script, /const canRetry = item\.status === 'failed' && Boolean\(state\.importJobId\)/)
  assert.match(script, /data-import-retry="\$\{escapeHtml\(id\)\}"[^>]*aria-label="重新抓取该篇" title="重新抓取该篇"/)
  assert.match(styles, /\.article-import-tool-icon\s*\{[\s\S]*width:\s*clamp\(18px,[\s\S]*height:\s*clamp\(18px/)
  assert.match(script, /function retryImportItem\(article\)[\s\S]*\/import\/\$\{encodeURIComponent\(state\.importJobId\)\}\/retry[\s\S]*body: JSON\.stringify\(\{ url: article\.url \}\)[\s\S]*await pollImportJob\(\)/)
  assert.match(script, /else if \(retry && article\) \{\s*retryImportItem\(article\)/)
  assert.match(styles, /\.article-import-entry--failed \.article-import-reading-card-viewport\s*\{[\s\S]*border-color:\s*var\(--danger-color\)/)
  assert.doesNotMatch(styles, /\.article-import-tool-button--delete::before/)
  assert.doesNotMatch(styles, /\.article-import-tool-button--retry::before/)
  assert.match(script, /importEditedIds: new Set\(\)/)
  assert.match(script, /const editedById = new Map\(state\.importItems[\s\S]*state\.importEditedIds\.has\(item\.id\)/)
  assert.match(script, /state\.importEditedIds\.add\(article\.id\)/)
  assert.match(script, /editedById\.get\(item\.id\)\.bodyMarkdown/)
})

test('article import editing reuses the full two-column article modal with live preview', () => {
  ;['articleEditorModal', 'articleTitleInput', 'articleBodyEditor', 'articleEditorCancel', 'articlePublishBtn', 'articleEditorPreviewBody'].forEach((id) => {
    assert.match(markup, new RegExp(`id="${id}"`))
  })
  assert.match(markup, /<textarea class="article-import-title-editor" id="articleTitleInput" rows="3" maxlength="120"/)
  assert.match(markup, /<textarea class="article-body-editor article-import-markdown-editor" id="articleBodyEditor" rows="20"/)
  assert.match(script, /openEditor\(article, 'import'\)/)
  assert.match(script, /state\.editorMode === 'import'[\s\S]*coverImage: payload\.coverImage[\s\S]*publishedAt: payload\.publishedAt/)
  assert.match(script, /function requestCloseEditor\(\)[\s\S]*openConfirm\([\s\S]*放弃未保存修改/)
  assert.doesNotMatch(script, /data-import-title=|data-import-body=|data-import-save=|data-import-cancel=|data-import-edit-panel=/)
  assert.match(styles, /\.modal-body\.article-editor-modal-body\s*\{[\s\S]*width:\s*min\(900px,[\s\S]*height:\s*min\(840px,[\s\S]*grid-template-rows:\s*auto minmax\(0,\s*1fr\);/)
  assert.match(styles, /\.article-editor-grid\s*\{[\s\S]*grid-template-columns:\s*minmax\(0,\s*55fr\) minmax\(0,\s*45fr\)/)
  assert.match(markup, /class="form-field article-editor-preview-field">[\s\S]*id="articleEditorPreviewBody"/)
  assert.doesNotMatch(markup, /article-preview-layout-toggle|data-article-preview-layout|btn-segment/)
  assert.match(markup, /article-reading-preview--stacked article-reading-layout--stacked article-reading-card-scroll/)
  assert.doesNotMatch(script, /previewLayout|setPreviewLayout|syncPreviewLayoutControls|normalizePreviewLayout|data-article-preview-layout/)
  assert.doesNotMatch(markup, /article-editor-preview-divider/)
  assert.doesNotMatch(markup, /<label>文章预览<\/label>/)
  assert.match(markup, /class="article-modal-actions modal-editor-actions">[\s\S]*id="articleEditorCancel"[\s\S]*id="articlePublishBtn"/)
  assert.match(styles, /\.modal-editor-actions\s*\{[\s\S]*display:\s*flex;[\s\S]*flex-direction:\s*row;/)
  assert.doesNotMatch(markup, /id="articleEditorClose"/)
  assert.match(markup, /id="articleTitleInput"[^>]*aria-label="文章标题"[^>]*placeholder="输入文章标题"/)
  assert.match(markup, /id="articleBodyEditor"[^>]*aria-label="文章正文（Markdown）"[^>]*placeholder="输入文章正文，支持 Markdown/)
  assert.doesNotMatch(markup, /<label for="articleTitleInput">标题<\/label>|<label for="articleBodyEditor">正文（Markdown）<\/label>|<label>文章封面<\/label>/)
  assert.match(styles, /\.article-import-title-editor\s*\{[\s\S]*height:\s*72px;[\s\S]*resize:\s*none[\s\S]*font-size:\s*18px;[\s\S]*line-height:\s*1\.45/)
  assert.doesNotMatch(styles, /article-preview-layout-toggle|\.btn-segment/)
  assert.match(styles, /\.article-import-markdown-editor\s*\{[\s\S]*height:\s*100%;[\s\S]*min-height:\s*0/)
  assert.doesNotMatch(styles, /\.article-import-markdown-editor\s*\{[^}]*font-family:/)
  assert.match(mainScript, /function resizeTextarea\(textarea\) \{\s*if \(textarea\.matches\('\.article-import-markdown-editor, \.import-source-textarea'\)\) \{\s*textarea\.style\.removeProperty\('height'\)\s*return/)
  assert.match(script, /window\.setTimeout\(render, 300\)/)
  assert.match(script, /generation !== state\.editorPreviewGeneration/)
})

test('removed import items stay removed during polling and reset with each new batch', () => {
  assert.match(script, /removedImportIds: new Set\(\)/)
  assert.match(script, /filter\(\(item\) => !state\.removedImportIds\.has\(item\.id\)\)/)
  assert.match(script, /function startImport\(\)[\s\S]*state\.removedImportIds\.clear\(\)[\s\S]*state\.importItems = urls\.map/)
  assert.match(script, /function resetImportWorkspace\(\)[\s\S]*state\.removedImportIds\.clear\(\)/)
})

test('article import reading type matches the mini program article scale', () => {
  assert.match(styles, /\.article-reading-preview h1\s*\{[\s\S]*font-size:\s*22px;[\s\S]*line-height:\s*1\.38/)
  assert.match(styles, /\.article-reading-body\s*\{[\s\S]*font-size:\s*16px;[\s\S]*line-height:\s*1\.7/)
})

test('article previews mark media-only blocks and use the mini program media-flow spacing', () => {
  assert.match(script, /function decorateReadingBodyElement\(element\)/)
  assert.match(script, /child\.classList\.add\('article-reading-block'\)/)
  assert.match(script, /child\.classList\.add\('article-reading-block--media'\)/)
  assert.match(script, /bodyHtml: normalizeReadingBodyHtml\(bodyHtml\)/)
  assert.match(script, /nodes\.editorPreviewBody\.innerHTML = result\.renderedHtml \|\| ''\s*\n\s*decorateReadingBodyElement\(nodes\.editorPreviewBody\)/)
  assert.match(styles, /--article-reading-content-gap:\s*10px/)
  assert.match(styles, /--article-reading-media-gap:\s*12px/)
  assert.match(styles, /\.article-reading-body\s*\{[\s\S]*display:\s*flex;[\s\S]*flex-direction:\s*column;[\s\S]*gap:\s*var\(--article-reading-content-gap\)/)
  assert.match(script, /const blockImages = Array\.from\(block\.querySelectorAll\('img'\)\)[\s\S]*image\.style\.marginBottom = blockImages\.indexOf\(image\) < blockImages\.length - 1[\s\S]*var\(--article-reading-media-gap\)/)
  assert.doesNotMatch(styles, /article-reading-text-edge-gap/)
  assert.doesNotMatch(script, /article-reading-text-edge-gap|hasMediaAtBoundary/)
})
