const assert = require('node:assert/strict')
const fs = require('node:fs')
const path = require('node:path')
const test = require('node:test')

const projectRoot = path.resolve(__dirname, '../../..')
const adminSource = path.join(projectRoot, 'admin/server/admin/src')

test('audio uploads are processed on the server before COS storage', () => {
  const dockerfile = fs.readFileSync(path.join(projectRoot, 'admin/deploy/secretbox.Dockerfile'), 'utf8')
  const routes = fs.readFileSync(path.join(projectRoot, 'admin/server/src/routes.js'), 'utf8')
  const normalization = fs.readFileSync(path.join(projectRoot, 'admin/server/src/modules/storage/audio-normalization.service.js'), 'utf8')
  const main = fs.readFileSync(path.join(adminSource, 'main.js'), 'utf8')
  const importer = fs.readFileSync(path.join(adminSource, 'import.js'), 'utf8')

  assert.match(dockerfile, /apk add --no-cache ffmpeg/)
  assert.match(routes, /router\.post\('\/api\/admin\/audios\/upload'/)
  assert.match(routes, /fieldName: 'audio'/)
  assert.match(routes, /const runSingleAudioUpload = createSingleTaskRunner\(\)/)
  assert.match(routes, /await runSingleAudioUpload\(async \(\) =>/)
  assert.match(routes, /error instanceof TaskBusyError[\s\S]*?tooManyRequests\(res, '音频正在处理中，请稍后再试'\)/)
  assert.match(routes, /processAudioUpload\(file, fields\)/)
  assert.match(normalization, /loudnorm=I=\$\{TARGET_LOUDNESS\}:TP=\$\{TRUE_PEAK\}:LRA=\$\{LOUDNESS_RANGE\}/)
  assert.match(normalization, /await fs\.rm\(tempDir, \{ recursive: true, force: true \}\)/)
  assert.match(main, /formData\.append\('audio', file, name\)/)
  assert.match(importer, /formData\.append\('audio', file, item\.originalFilename\)/)
  assert.doesNotMatch(main, /\/api\/admin\/audios\/upload\/prepare/)
  assert.doesNotMatch(importer, /\/api\/admin\/audios\/upload\/prepare-batch/)
})
