const assert = require('node:assert/strict')
const fs = require('node:fs')
const path = require('node:path')
const test = require('node:test')

const adminSource = path.resolve(__dirname, '../admin/src')

test('admin keeps a desktop layout with a 1200px minimum canvas width', () => {
  const shell = fs.readFileSync(path.join(adminSource, 'shell.js'), 'utf8')
  const markup = fs.readFileSync(path.join(adminSource, 'index.html'), 'utf8')
  const script = fs.readFileSync(path.join(adminSource, 'main.js'), 'utf8')
  const styles = fs.readFileSync(path.join(adminSource, 'styles.css'), 'utf8')

  assert.match(styles, /html,[\s\S]*?body \{\s*min-width: 1200px;/)
  assert.match(styles, /\.admin-layout \{\s*min-width: 1200px;/)
  assert.match(styles, /--sidebar-w: 120px;/)
  assert.match(styles, /\.nav-item \{[\s\S]*?padding: 0 10px;/)
  assert.doesNotMatch(styles, /@media \(min-width: 1081px\)/)
  assert.doesNotMatch(styles, /@media \(max-width/)
  assert.doesNotMatch(styles, /\.mobile-card-table/)
  assert.doesNotMatch(shell, /mobile-nav|sidebar-overlay|admin-menu-btn|mobile-open/)
  assert.doesNotMatch(markup, /mobile-card-table/)
  assert.doesNotMatch(script, /mobile-card-table/)
  assert.match(styles, /\.data-table \{[^}]*width: 100%;/)
  assert.doesNotMatch(styles, /\.data-table \{[^}]*?(?:min-width|max-width|table-layout):/)
  assert.doesNotMatch(styles, /\.content-table-[^{]+\{[^}]*?(?:width|min-width|max-width|table-layout):/)
  assert.match(styles, /\.content-edit-table \{\s+table-layout: fixed;/)
  assert.doesNotMatch(styles, /\.content-edit-table \{[^}]*?(?:width|min-width|max-width):/)
  assert.doesNotMatch(styles, /\.image-table \{[^}]*?(?:width|min-width|max-width|table-layout):/)
})
